/**
 * Takes a date object and returns a string like Jun 2nd, 2023
 * Generated by ChatGPT from the prompt:
 * write a javascript function that will take a date object as an argument
 * and return a formatted string representing the date like Jun 2nd, 2022
 */
export default function formatDate(date) {
  const months = [
    "Jan",
    "Feb",
    "Mar",
    "Apr",
    "May",
    "Jun",
    "Jul",
    "Aug",
    "Sep",
    "Oct",
    "Nov",
    "Dec"
  ]
  const month = months[date.getMonth()]
  const day = date.getDate()
  const year = date.getFullYear()
  let suffix = "th"

  if (day === 1 || day === 21 || day === 31) {
    suffix = "st"
  } else if (day === 2 || day === 22) {
    suffix = "nd"
  } else if (day === 3 || day === 23) {
    suffix = "rd"
  }

  return month + " " + day + suffix + " " + year
}
